server_connect_timeout: 5000
listeners:
- query_port: 25565
  motd: ''
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 200
  tab_size: 70
  force_default_server: true
  proxy_protocol: false
  priorities:
  - LOBBY
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: 200
ip_forward: true
groups:
  HAnh:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 2997c98a-def1-4a38-8637-2987c7a564b9
online_mode: false
forge_support: true
disabled_commands:
- server
servers:
  OP_SKYBLOCK:
    motd: '&1Skyblock'
    address: 172.104.33.240:11145
    restricted: false
  FACTIONS:
    motd: '&1Faction'
    address: localhost:19999
    restricted: false
  LOBBY:
    motd: '&dLOBBY'
    address: 139.162.6.103:12369
    restricted: false
